### ISSUE TITLE
Issue installing required packages

### ISSUE THREAD

**Issue by oskasf** [Emvlt/MAPHIS#1]
@Emvlt 
I'm trying to install the `CRAFT` package (which I believe is this one [here](https://github.com/clovaai/CRAFT-pytorch)) but I can't seem to install. Am I missing something? Do I need to have the repo cloned in this directory as well?

Perhaps it would be worthing add a .yml file to the repo to make package installation a bit easier.

**Comment by Emvlt** [comment]
@oskasf 
You just have to clone their repo and download the weights and save them in the appropriate folder.
I will push the CRAFT package and the saved weights today. :) 
I agree that it is not straightforward, sorry about that.

**Comment by Emvlt** [comment]
Included the submodule craft, download weights from : 

- https://drive.google.com/file/d/1XSaFwBkOaFOdtk4Ane3DFyJGPRw6v5bO/view
- https://drive.google.com/file/d/1Jk4eGD7crsqCCg9C9VjCLkMN3ze8kutZ/view

and put them in a folder named "weights" in "CRAFT"
